### ISSUE TITLE
Using tslint or any other linter

### ISSUE THREAD

**Issue by przepompownia** [iamcco/vim-language-server#22]
```sh
 $ tslint --init
 $ tslint -c tslint.json '{.,test}/src/**/*.ts' | wc -l
2281
```
Most of these two thousand are suggestions of missing semicolons or using constant when a variable was never reassigned. Most of these can be fixed automatically by `tslint`. What do you think about conforming to these suggestions and checking it by CI before merging?

**Comment by iamcco** [comment]
make sense
