### ISSUE TITLE
It seems that this language server doesn't display warning messages.

### ISSUE THREAD

**Issue by steelbluelee** [iamcco/vim-language-server#27]
I installed coc-vimlsp and this language server. They seem to work well.
They display error messages well. But I cannot see any warning messages with init.vim file
which vint display warnings for. Doesn't this language server support warning? If it support,
what should I check?

thx

**Comment by iamcco** [comment]
You should just install coc-vimlsp or this language server. It only display errors by vim-vimlparser parser.
