### ISSUE TITLE
VLS not sedning function info in the textDocument/completion response.

### ISSUE THREAD

**Issue by iddinev** [iamcco/vim-language-server#49]
**Describe the bug**
VLS is not sending any info in the **detail** or **documentation** fileds in the response to the **textDocument/completion** method from the LC for functions.

**To Reproduce**
Issue was observed on vim8:

> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     

1. Use a min-vimrc from [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim)
adding the appropriate VLS config line & deoplete plugin. Or use my min-vimrc that has all the needed extra configs:
>call plug#begin('~/.vim/plugged')
>
>Plug 'autozimu/LanguageClient-neovim', {
>    \ 'branch': 'next',
>    \ 'do': 'bash install.sh',
>    \ }
>
>  Plug 'Shougo/deoplete.nvim'
>  let g:deoplete#enable_at_startup = 1
>
>  Plug 'Shougo/neopairs.vim'
>
>  Plug 'Shougo/neoinclude.vim'
>
>  Plug 'Shougo/context_filetype.vim'
>
>  Plug 'roxma/nvim-yarp'
>
>  Plug 'roxma/vim-hug-neovim-rpc'
>
>  Plug 'Shougo/neco-syntax'
>
>  Plug 'Shougo/echodoc.vim'
>  let g:echodoc#enable_at_startup = 1
>  highlight link EchoDocPopup Pmenu
>  "let g:echodoc#type = 'popup'
>  set noshowmode
>
> Plug 'dense-analysis/ale'
>  " Shell linter requires 'shellcheck'.
>  let g:ale_linters = {
>  \ 'sh': ['shellcheck', 'shell'],
>  \ 'python': ['mypy', 'pylint', 'pycodestyle']
>  \ }
>  let g:ale_echo_msg_error_str = 'E'
>  let g:ale_echo_msg_warning_str = 'W'
>  let g:ale_echo_msg_format = '[%linter%] [%code%] [%severity%] %s'
>  let g:ale_disable_lsp = 1
>  let g:ale_completion_enabled = 0
>
>  " Used as a styler, requires 'vint'.
>  Plug 'Vimjas/vint'
>
>call plug#end()
>
>augroup filetype_rust
>    autocmd!
>    autocmd BufReadPost *.rs setlocal filetype=rust
>augroup END
>
>" Always draw sign column. Prevent buffer moving when adding/deleting sign.
>"set signcolumn=yes
>
>let g:LanguageClient_serverCommands = {
>    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
>    \ 'sh': ['bash-language-server', 'start'],
>    \ 'vim': ['vim-language-server', '--stdio'],
>   \ 'python': ['pyls'],
>    \ }
>let $RUST_BACKTRACE = 1
>let g:LanguageClient_diagnosticsEnable = 0
>let g:LanguageClient_virtualTextPrefix = ''
>let g:LanguageClient_loggingLevel = 'DEBUG'
>let g:LanguageClient_loggingFile =  expand('\~/.vim/LanguageClient.log')
>let g:LanguageClient_serverStderr = expand('\~/.vim/LanguageServer.log')

2. Open an empty .vim file.
3. Try to reproduce the action from the .gif on the front page of the [VLS project](https://user-images.githubusercontent.com/5492542/81493984-909c2e80-92d7-11ea-9638-d7be3e18e1d1.gif)
4. No extra info is show when cycling through the completion menu entries (as opposed to the info shown in the VLS .gif)

**Expected behavior**
Information is available during completion menu cycling.

**Screenshots**
![Peek 2020-11-18 18-00](https://user-images.githubusercontent.com/11410938/99554668-1fe17780-29c8-11eb-99ab-db06ffd7a340.gif)

**Desktop (please complete the following information):**
 - OS: Arch linux.

Log:
NOTE: Log is cut so it can fit pastebin's lenght requrements, but the initialization and example. of missing info in the fileds is present.
[LanguageClient-neovim.log](https://pastebin.com/8Jufpkgn)

**Comment by iamcco** [comment]
function doc's size is too large, it only return on complete resolve. seems LanguageClient-neovim does not implement the feature.

**Comment by iddinev** [comment]
(Will be) fixed upstream by https://github.com/autozimu/LanguageClient-neovim/pull/1043
This issue is closed.
