### ISSUE TITLE
infinite(?) loop frequently triggered

### ISSUE THREAD

**Issue by puremourning** [iamcco/vim-language-server#54]
**Describe the bug**

When using the vim-language-server I frequently find the server stuck unresponsive, consuming 100% of a CPU core. The only resolution is to manually kill the node exe in Activity Monitor.

I've attached vimspector to it, and got the following stack trace:

```
- Thread 1: Node (36045) (Paused on user request)
  1001: exports.signatureHelpProvider@index.js:26177
  1002: (anonymous function)@index.js:1035
  1003: handleRequest@index.js:1682
  1004: processMessageQueue@index.js:1572
  1005: (anonymous function)@index.js:1562
  1006: processImmediate@timers:463

```

Importantly, it's stuck inside that `match` call. The value of `preSegment` is:

<img width="662" alt="Screenshot 2021-04-03 at 16 40 20" src="https://user-images.githubusercontent.com/10584846/113483444-56adbb00-949b-11eb-8b01-bd03c7492974.png">

i.e. 
```
Watches: ----
Expression: preSegment
 *- Result: "        \ split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"),"
```

I can confirm that if I set a breakpoint on the next line and continue, it never fires, or seems not to.

**To Reproduce**

Difficult to do reliably, but it almost always seems to coincide with the server just reporting "Unexpected token EOL", often while writing a function call.

I have listed the full ycmd (LSP client) log here, which includes a full trace of the messages between client and server:

**Expected behavior**

Server does not get stuck pegging a CPU.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3 

Log:  https://gist.github.com/puremourning/c94cdbd9d52337ef6182f4e38c04d011

**Comment by iamcco** [comment]
Which node process ? `scan.js` or `server`?

It's seems can not be the `match` line since it's standard function of string.

Don't know if it relative to vimlparser like https://github.com/iamcco/coc-vimlsp/issues/5#issuecomment-519170844

Latest version has improve  detect for parser.

**Comment by puremourning** [comment]
Good question. I don't know - I will check next time this happens. Sorry, I did not realise that there are two processes.

FWIW I'm confident that the process I was attached to was stuck in that match call. I can reproduce it in the node command line:


```
ben@BenMBP viml % node
Welcome to Node.js v15.5.1.
Type ".help" for more information.
> s = '        \\ split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"),'
'        \\ split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"),'
> preSegment = s
'        \\ split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"),'
> const m = preSegment.match(/([\w#&:]+)[ \t]*\(([^()]*|\([^)]*\))*$/);
{ never returns}
```

**Comment by puremourning** [comment]
Happened again.

<img width="943" alt="Screenshot 2021-04-04 at 17 10 48" src="https://user-images.githubusercontent.com/10584846/113514846-ca69c980-9568-11eb-82ab-ed32b013f184.png">

Very similar to the other one.

The command line for the pid is suggests it's the sever not the indexer:

```
Watches: ----
Expression: process.argv
  - Result: Array(3) ["/usr/local/Cellar/node/15.5.1/bin/node", "/Users/ben/Development/lsp/viml/node_modules/.bin/…", "--stdio"]
    - length (number): 3
    - 0 (string): "/usr/local/Cellar/node/15.5.1/bin/node"
    - 1 (string): "/Users/ben/Development/lsp/viml/node_modules/.bin/vim-language-server"
    - 2 (string): "--stdio"
    + __proto__ (Object): Array(0) [, …]
Expression: process.argv0
 *- Result: "node"

```

**Comment by iamcco** [comment]
It's weird, can you paste the vim code here when it happend ?

**Comment by iamcco** [comment]
seems regex too complex, it takes 20 mins to execute.

```
var preSegment = "           \ function( 's:HandleSymbolSearchResults' )"
var m = preSegment.match(/([\w#&:]+)[ \t]*?\(([^()]*|\([^)]*?\))*?$/)
console.log(m);
```
