### ISSUE TITLE
The latest version of npm and the latest version of GitHub are wrong.

### ISSUE THREAD

**Issue by kazukazuinaina** [iamcco/vim-language-server#59]
Hello, maintainer!
Thanks for your creating great language-server!
I did find one problem.
On GitHub, vim-language-server's latest version is v2.0.0, but npm's latest version is v2.2.0.
Which is correct?

## GitHub's latest version
> https://github.com/iamcco/vim-language-server/releases/tag/v2.0.0

## npm's latest version
> https://www.npmjs.com/package/vim-language-server

**Comment by iamcco** [comment]
v2.0.0 is out of date, update now.

**Comment by kazukazuinaina** [comment]
Thanks!
