### ISSUE TITLE
Unexpected Token Error For Commented Dictionaries

### ISSUE THREAD

**Issue by TerryChau** [iamcco/vim-language-server#76]
```
        let g:ale_linters = {
                    \ 'asm':['gcc'],
                    \ 'c':['clangd'],
                    \ 'cpp': ['clangd'],
                    "\ 'c':['gcc','clangd'],
                    "\ 'cpp': ['gcc', 'clangd'],
                    \ 'css':['stylelint'],               <-- lines with unexpected token: <EOL> error at ]
                    \ }
```

When I comment out certain lines (lines 5-6) in a dictionary, the vim-language-server reports an "unexpected token: \<EOL\>" error in the subsequent line.  However, to the best of my knowledge, the vim script above is valid.  Can this error removed?

I am using the following version of vim-language-server with ALE.

pkgname=vim-language-server
pkgver=2.2.10
pkgrel=1
pkgdesc="VimScript language server"
arch=('any')
url="https://github.com/iamcco/vim-language-server"
license=('MIT')
depends=('nodejs')
makedepends=('npm')
source=("$pkgname-$pkgver.tgz::https://registry.npmjs.org/$pkgname/-/$pkgname-$pkgver.tgz")
sha256sums=('ee09909846bc02880e240b3b5c682ef18235c97243ab24227034f2f27530a771')

**Comment by iamcco** [comment]
duplicate https://github.com/iamcco/vim-language-server/issues/43
