### ISSUE TITLE
vint support

### ISSUE THREAD

**Issue by oblitum** [iamcco/vim-language-server#8]
I'm currently using coc-vimlsp but can't get rid of ALE b/c it picks on vint, which provides some nice code suggestions, so I'm using both, with some duplicated diagnostics. If coc-vimlsp or vim-language-server supported vint for linting I'd not need to use it through ALE.

**Comment by iamcco** [comment]
coc-vimlsp and vim-language-server will not support vint as a linter. I have add an option to disable diagnostic from coc-vimlsp or vim-language-server. if you do want to use coc with vint then have a look at https://github.com/iamcco/coc-diagnostic

**Comment by oblitum** [comment]
ok.
