### ISSUE TITLE
Reported error for comment after an indented let=<<

### ISSUE THREAD

**Issue by Aster89** [iamcco/vim-language-server#82]
Copied from https://github.com/vim/vim/issues/11642 / https://github.com/ycm-core/lsp-examples/issues/33

### Steps to reproduce

1. Open a vimscript file and fill it with the following content:
```viml
fun SomeFun()
  let text =<< trim END
  Some text
  END
endf
" a comment
```
2. Observe the syntax coloring of `"`
3. Hit <kbd>Escape</kbd><kbd>G</kbd><kbd>A</kbd><kbd>Enter</kbd><kbd>Enter</kbd>.
4. See the error.

Here's a screencast:

[![asciicast](https://asciinema.org/a/t9eVPrfsP6CAAJwo4AiaLUKkL.svg)](https://asciinema.org/a/t9eVPrfsP6CAAJwo4AiaLUKkL)

---

Note there's nothing after the closing `END` and there's as much space before as before `let`. This is consistent with [`let {var-name} =<< [trim] [eval] {endmarker}`'s documentation](https://vimhelp.org/eval.txt.html#%3Alet%3D%3C%3C), specifically

> The last line should end only with the `{endmarker}` string without any other character.

and
> The marker must line up with "`let`".

### Expected behaviour

Correct syntax coloring and no error.

### Version of Vim

9.0 patch 1-910

### Environment

Operating system: up-to-date Archlinux
Terminal: URxvt
Value of $TERM: rxvt-unicode-256color
Shell: Bash

**Comment by iamcco** [comment]
vimlparser bug https://github.com/vim-jp/vim-vimlparser/issues/188

**Comment by iamcco** [comment]
Close https://github.com/iamcco/vim-language-server/commit/f6e1808e441c64f47f6fb86886eb9ad5a4e74156
