### ISSUE TITLE
Function name can start with '_'

### ISSUE THREAD

**Issue by xieshiyao** [iamcco/vim-language-server#9]
I got the error shown in the picture in my `.vimrc`, but actually, this function works fine with either `vim` or `neovim`. I know that (neo)vim's document `eval.txt` says that a function name must start with a capital, but I think it's just a problem with that document.

![Screenshot from 2019-07-21 11-14-41](https://user-images.githubusercontent.com/44437715/61586513-c9ccac00-aba8-11e9-898d-bcb60cb51638.png)

I start the function name with `_` for two reasons:

1. This way, it will never conflict with functions defined by plugins I installed

2. I map it to some keys, so will never need to call it by name and I don't want to see any autocompletion about it when I type `:call V<Tab>`

-----------------------------------------------

After reading`init.vim` written by someone else, I realize that what I should do is to apply `:s/_/s:/`to my function name. But I still consider this as inconsistency between implementaion and document. What do you think about it?
 @justinmk

**Comment by iamcco** [comment]
This error is throw by https://github.com/vim-jp/vim-vimlparser, i think @tyru should also have a look at on this.

**Comment by tyru** [comment]
@iamcco please file issue if that's a vimlparser's bug.

**Comment by tyru** [comment]
Ah okay, I got it.
I created issue. https://github.com/vim-jp/vim-vimlparser/issues/133
