### ISSUE TITLE
Tag v2.3.1 is missing from the repository

### ISSUE THREAD

**Issue by alexmurray** [iamcco/vim-language-server#90]
I can see the release at https://github.com/iamcco/vim-language-server/releases/tag/2.3.1 but there doesn't appear to be any corresponding tag at https://github.com/iamcco/vim-language-server/tree/v2.3.1(whereas the v.2.3.0 tag exists for the v2.3.0 release)

**Comment by iamcco** [comment]
Thanks, fix

**Comment by alexmurray** [comment]
Thank you :)
