### ISSUE TITLE
Just aquick question. How do I get this to run with nvim-lsp

### ISSUE THREAD

**Issue by Unaimend** [iamcco/vim-language-server#96]
I tried `lspconfig.vim-language-server.setup{}` which lua obv. did not like due to the `-` in the name. Then I just symlinked `vim-language-server` to `vlsp` and tried `lspconfig.vlsp.setup{}`

But this results in this error 
`[lspconfig] Cannot access configuration for vlsp. Ensure this server is listed in server_configurations.md or added as a custom server.`

I googled the error but did not find any useful information

**Comment by LZDQ** [comment]
The [doc](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#vimls). Change it to `vimls`. @Unaimend
